name: Build and Deploy to EC2 Instance

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-to-ECR:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
            | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Create .env file
        run: |
          echo "${{ secrets.DOTENV_FILE }}" > .env
          ls -l
          cat .env

      - name: Build Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7} 
          docker build -t connect3v3:$IMAGE_TAG .
          docker tag connect3v3:$IMAGE_TAG ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
          docker tag connect3v3:$IMAGE_TAG ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push to ECR
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy FastAPI to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > ec2_key.pem
          chmod 400 ec2_key.pem

          scp -o StrictHostKeyChecking=no -i ec2_key.pem .env ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/.env
          scp -o StrictHostKeyChecking=no -i ec2_key.pem docker-compose.yml ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/docker-compose.yml
          scp -o StrictHostKeyChecking=no -i ec2_key.pem Caddyfile ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/Caddyfile

          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} "\
            docker network inspect mynetwork >/dev/null 2>&1 || docker network create mynetwork && \
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
              | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }} && \
            cd /home/ec2-user && \
            docker-compose pull && \
            docker-compose up -d
          "